/* Story content for template 4.
   Placeholder editorial copy written for the template: replace with the
   Maison's approved text before launch. Images are Unsplash stand-ins. */

const img = (id, w = 1600) => `https://images.unsplash.com/photo-${id}?w=${w}&q=78&auto=format&fit=crop`;

window.STORIES = [
  {
    id: 'material',
    topic: 'Material',
    tint: '#e6d2b5',
    title: 'What Is Red Sandalwood?',
    date: '18 September 2026',
    time: '6 min read',
    image: '1702001145743-094b0b7ead51',
    alt: 'Cross-section of a sandalwood log showing the red heartwood',
    lede: 'A slow-growing tree from the Eastern Ghats, a heartwood dense enough to sink in water, and a trade the world agreed to protect.',
    body: [
      'Red sandalwood is the heartwood of Pterocarpus santalinus, a tree found naturally in a narrow belt of dry hill forest in the southern Eastern Ghats of India. It grows slowly, and the deep red core that gives it its name forms over many years inside the paler sapwood.',
      'Cut and polished, the heartwood is heavy, cool to the touch and remarkably fine in the grain. Its colour runs from blood red to a deep violet brown, and it darkens gently with handling.',
      'Because wild trees were cut faster than they could regrow, the species is listed under Appendix II of CITES, the international treaty on trade in endangered species. Every legal movement of the wood needs paperwork that shows where it came from.',
      'That is why we work with this one material and nothing else, and why every piece we make leaves the workshop with its record.',
    ],
    quote: 'One material, understood deeply.',
    slides: [
      { h: 'Where it grows', t: 'A narrow belt of dry hill forest in the southern Eastern Ghats of India.', img: '1768057887146-3b2a3d2775ef' },
      { h: 'The heartwood', t: 'A dense red core that forms slowly inside the paler sapwood.', img: '1702001145743-094b0b7ead51' },
      { h: 'Heavy and fine', t: 'Dense enough to sink in water, with a grain that polishes to a soft sheen.', img: '1697507695420-04623ccff2af' },
      { h: 'Protected by treaty', t: 'Listed under CITES Appendix II. Every legal movement needs documentation.', img: '1690983322335-ddb0eca0229e' },
      { h: 'Why only this wood', t: 'One material, understood deeply. Every piece leaves with its record.', img: '1784570343031-649cce9a185c' },
    ],
  },
  {
    id: 'craft',
    topic: 'Craft',
    tint: '#c4c4a0',
    title: 'Every Piece Begins as a Reading',
    date: '9 September 2026',
    time: '5 min read',
    image: '1606077089563-cff5a4f3d3d9',
    alt: 'Carving chisels laid out beside an artisan at work',
    lede: 'The artisan studies the grain before the first cut. The wood decides what it will become. The hand follows.',
    body: [
      'Nothing is cut to a drawing first. Each block is turned in the hand and read: where the colour is deepest, where the grain runs straight, where it twists around an old knot.',
      'Only then is a form chosen. A bead, a comb or a small vessel is shaped to follow the grain rather than fight it, which is why no two pieces are quite alike.',
      'Finishing is slow. Surfaces are worked by hand until the red deepens and the wood feels cool and smooth in the palm.',
      'Every finished piece is inspected, numbered and registered before it is wrapped with its record.',
    ],
    quote: 'The wood decides what it will become.',
    slides: [
      { h: 'Select', t: 'Heartwood is chosen block by block, for colour, density and the line of the grain.', img: '1606077089563-cff5a4f3d3d9' },
      { h: 'Shape', t: 'Cuts follow the wood, not a template. The form is set by what the grain allows.', img: '1721508490084-1b1de5b230d4' },
      { h: 'Finish', t: 'Surfaces are worked by hand until the colour deepens.', img: '1779031242469-ef2e794987b0' },
      { h: 'Inspect', t: 'Each piece is checked, numbered and registered.', img: '1497219055242-93359eeed651' },
      { h: 'Present', t: 'Pieces leave with their material, batch and provenance record.', img: '1636978669347-ebc543a814f3' },
    ],
  },
  {
    id: 'provenance',
    topic: 'Provenance',
    tint: '#ddb39a',
    title: 'Every Piece Keeps a Record',
    date: '28 August 2026',
    time: '4 min read',
    image: '1768057887146-3b2a3d2775ef',
    alt: 'Misty hills and forest at sunrise in the Eastern Ghats',
    lede: 'All pieces are individually numbered and registered. Provenance documentation is available on request.',
    body: [
      'A piece of red sandalwood is only as trustworthy as the paper that follows it. We keep that paper, from the source of the wood to the hand that finished it.',
      'Each batch is logged when it arrives, with its documented origin and the permits that allowed it to move. Pieces cut from that batch carry its reference.',
      'When a piece is finished it is numbered and entered in our register. The number on your piece matches a record we hold, and a copy is available on request.',
    ],
    quote: 'The number on your piece matches a record we hold.',
    slides: [
      { h: 'Source', t: 'Wood arrives only with documented origin and the permits to move it.', img: '1768057887146-3b2a3d2775ef' },
      { h: 'Batch', t: 'Every batch is logged on arrival and given a reference.', img: '1702001145743-094b0b7ead51' },
      { h: 'Processing', t: 'Pieces cut from a batch carry its reference through the workshop.', img: '1606077089563-cff5a4f3d3d9' },
      { h: 'Registration', t: 'Finished pieces are numbered and entered in the register.', img: '1646534607539-6355deaf495c' },
      { h: 'On request', t: 'A copy of the record is available for any piece we have made.', img: '1784034008011-1cf10e243b67' },
    ],
  },
  {
    id: 'vault',
    topic: 'Vault',
    tint: '#e3bd7f',
    title: 'The 2011 Vault',
    date: '14 September 2026',
    time: '3 min read',
    image: '1697507695420-04623ccff2af',
    alt: 'Close view of dark red heartwood grain',
    lede: '21 pieces. Aged heartwood. Each numbered.',
    body: [
      'The wood was sourced in 2011. It has been waiting since then for the right hands and the right moment. Both have arrived.',
      'Fifteen years of rest has settled the colour and tightened the surface. The edition is limited by the wood itself: when these blocks are used, the edition closes.',
      'Each of the 21 pieces is numbered and registered, and leaves with its own record.',
    ],
    quote: 'Both have arrived.',
    slides: [
      { h: 'Sourced in 2011', t: 'A single documented batch, set aside the year it arrived.', img: '1697507695420-04623ccff2af' },
      { h: 'Left to rest', t: 'Fifteen years of rest settled the colour and tightened the surface.', img: '1690983322335-ddb0eca0229e' },
      { h: 'Twenty-one pieces', t: 'The edition is limited by the wood itself.', img: '1784570343031-649cce9a185c' },
      { h: 'Each numbered', t: 'Every piece is numbered, registered and sent with its record.', img: '1646185843593-9d7dd6a957cb' },
      { h: 'Reserve a piece', t: 'Pieces are offered privately first. Enquire to reserve.', img: '1770816307472-945144576a1f' },
    ],
  },
  {
    id: 'gifting',
    topic: 'Gifting',
    tint: '#cfae8a',
    title: 'Gifts That Carry a Record',
    date: '2 September 2026',
    time: '4 min read',
    image: '1770816307472-945144576a1f',
    alt: 'An open wooden keepsake box in a pool of light',
    lede: 'For a milestone, a client or a home. Every gift leaves with its number and its story.',
    body: [
      'A gift in red sandalwood is chosen to be kept. We help choose the piece, prepare the presentation and include the record, so the person receiving it knows exactly what they hold.',
      'For corporate and hospitality gifting we work in small, considered quantities, with numbering and documentation for each piece.',
      'Designer collaborations and bespoke commissions begin with a private conversation.',
    ],
    quote: 'Chosen to be kept.',
    slides: [
      { h: 'Personal', t: 'A single piece, presented with its record.', img: '1770816307472-945144576a1f' },
      { h: 'Corporate', t: 'Small, considered quantities, each piece numbered.', img: '1549315393-aeac60e09d29' },
      { h: 'Milestones', t: 'For the days worth remembering in a material that lasts.', img: '1646185843593-9d7dd6a957cb' },
      { h: 'Hospitality', t: 'Pieces for rooms and guests, documented and cared for.', img: '1636978669347-ebc543a814f3' },
      { h: 'Collaborations', t: 'Designer and bespoke work begins with a private conversation.', img: '1607437817193-3b3b029b5b75' },
    ],
  },
  {
    id: 'twentyone',
    topic: 'Journal',
    tint: '#d9c3a3',
    title: 'Why We Stopped at 21 Pieces',
    date: '14 June 2026',
    time: '6 min read',
    image: '1778616364918-34490657598f',
    alt: 'A hand holding a strand of prayer beads',
    lede: 'The size of an edition should be set by the wood, not by demand.',
    body: [
      'When we opened the 2011 batch, we laid every block out and asked a simple question: how many pieces does this wood want to become?',
      'The answer was 21. More would have meant cutting around flaws or using thinner stock. Fewer would have wasted good heartwood.',
      'So the edition is 21, each numbered, and it will not be repeated.',
    ],
    quote: 'The answer was 21.',
    slides: [
      { h: 'The question', t: 'How many pieces does this wood want to become?', img: '1778616364918-34490657598f' },
      { h: 'Laying it out', t: 'Every block from the 2011 batch, read side by side.', img: '1702001145743-094b0b7ead51' },
      { h: 'The answer', t: '21 pieces, without cutting around flaws.', img: '1784570343031-649cce9a185c' },
      { h: 'Not repeated', t: 'When the wood is used, the edition closes.', img: '1697507695420-04623ccff2af' },
    ],
  },
  {
    id: 'carver',
    topic: 'Journal',
    tint: '#cdbb9c',
    title: 'What a Master Carver Reads in the Grain',
    date: '2 June 2026',
    time: '5 min read',
    image: '1779031242469-ef2e794987b0',
    alt: 'A carver working a piece of wood by hand in low light',
    lede: 'Colour, direction and weight. Three things a carver checks before the first cut.',
    body: [
      'The first thing a carver looks at is colour. The deepest red usually sits closest to the centre of the tree, and that is where the finest pieces come from.',
      'Next is direction. Grain that runs straight will take fine detail; grain that curls will reward a rounder, simpler form.',
      'Last is weight. A block that feels heavy for its size is dense and stable, and will hold its shape for generations.',
    ],
    quote: 'Colour, direction and weight.',
    slides: [
      { h: 'Colour', t: 'The deepest red sits closest to the centre of the tree.', img: '1697507695420-04623ccff2af' },
      { h: 'Direction', t: 'Straight grain takes detail. Curling grain wants a rounder form.', img: '1776546369447-5429b28c491c' },
      { h: 'Weight', t: 'Heavy for its size means dense, stable and long-lived.', img: '1779031242469-ef2e794987b0' },
      { h: 'Then the cut', t: 'Only after all three does the first cut happen.', img: '1497219055242-93359eeed651' },
    ],
  },
];

window.STORY_IMG = img;
